spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/liquibase
    password: shawon

  application:
    name: Liquibase_demo
  liquibase:
    enabled: 'true'
    change-log: classpath:db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true



